name: ccf_reseller_web_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  flutter_datetime_picker: ^1.5.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  logger: ^1.0.0
  http: ^0.13.1

  font_awesome_flutter: ^9.0.0
  provider: ^5.0.0
  transformer_page_view: ^0.1.6
  quiver: ^3.0.0
  flushbar: ^1.9.1
  charts_flutter: ^0.10.0
  flutter_statusbarcolor: ^0.2.3
  google_maps_flutter: ^2.0.2
  pin_entry_text_field: ^0.1.4
  # package_info: ^0.4.3+4
  flutter_facebook_login: ^3.0.0
  # flutter_secure_storage: ^4.1.0
  shared_preferences: ^2.0.6
  firebase_core: ^1.0.2
  firebase_core_web: ^1.0.1
  firebase_auth: ^1.0.0
  firebase_messaging: ^9.0.0
  firebase_messaging_web: ^1.0.1
  image_picker: ^0.8.2
  image_picker_for_web: ^2.1.0
  sms_autofill: ^1.3.1
  pin_code_fields: ^7.0.0
  select_dialog: ^2.0.0
  flutter_form_builder: ^6.0.0-nullsafety.1
  awesome_dialog: ^1.3.2
  grouped_list: ^4.0.0
  device_info_plus: ^2.1.0
  flutter_picker: ^2.0.1
  async: ^2.5.0-nullsafety.3
  path_provider: ^2.0.1
  file_picker: ^3.0.3
  http_parser: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  generate: true
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/256.png
    - assets/images/512.png
    - assets/images/1024.png
    - assets/images/chokchey.png
    - assets/images/facebook.png
    - assets/images/phone.png
    - assets/images/english.png
    - assets/images/khmer.png
    - assets/images/khmercurrency.png
    - assets/images/wing.png
    - assets/images/ppcbank.png
    - assets/images/acleda.png
    - assets/images/101.png
    - assets/images/102.png
    - assets/images/103.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
